# Generated by Django 2.1.7 on 2019-02-24 05:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='token',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
