# Generated by Django 2.1.7 on 2019-03-16 09:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0002_auto_20190224_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='GameSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_game', models.UUIDField()),
                ('games_in_series', models.IntegerField(default=10)),
                ('players', models.ManyToManyField(to='gameapi.Token')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.BooleanField()),
                ('game_result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gameapi.GameResult')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gameapi.Token')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('registration_finishes_at', models.DateTimeField(blank=True, null=True)),
                ('tournament_finished_at', models.DateTimeField(blank=True, null=True)),
                ('players', models.ManyToManyField(to='gameapi.Token')),
            ],
        ),
        migrations.AddField(
            model_name='gameseries',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gameapi.Tournament'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='game_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gameapi.GameSeries'),
        ),
    ]
